client_id = "b6a6c785d64593d4fbabf601f3b885c2"
name = "SouqMetrics"
application_url = "https://souqmetrics.co"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://frgzxxszpzclhnkgmkuw.supabase.co/functions/v1/shopify-webhooks"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "https://frgzxxszpzclhnkgmkuw.supabase.co/functions/v1/shopify-webhooks"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "https://frgzxxszpzclhnkgmkuw.supabase.co/functions/v1/shopify-webhooks"

[access_scopes]
scopes = "read_customers,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://frgzxxszpzclhnkgmkuw.supabase.co/functions/v1/shopify-callback"
]

[app_preferences]
url = "https://app.souqmetrics.co/#/overview"

